/**
 * Semantic icon key → Tabler component.
 *
 * Explicit named imports only. The library ships ~5,900 icons; importing it
 * wholesale would defeat tree-shaking and let the icon set drift.
 */

import {
  IconBarbell,
  IconBasket,
  IconBolt,
  IconBook,
  IconBriefcase,
  IconBuildingBank,
  IconBuildingStore,
  IconBus,
  IconCake,
  IconCar,
  IconCash,
  IconCertificate,
  IconChartLine,
  IconCoins,
  IconCoffee,
  IconCreditCard,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceTv,
  IconDroplet,
  IconFlame,
  IconGasStation,
  IconGift,
  IconGlassFull,
  IconHeart,
  IconHome,
  IconMeat,
  IconMovie,
  IconMusic,
  IconParking,
  IconPaw,
  IconPhone,
  IconPigMoney,
  IconPill,
  IconPizza,
  IconPlant2,
  IconReceipt,
  IconSchool,
  IconScissors,
  IconShieldCheck,
  IconShoppingBag,
  IconSpray,
  IconStethoscope,
  IconTag,
  IconTicket,
  IconToolsKitchen2,
  IconTools,
  IconTrain,
  IconUmbrella,
  IconUsers,
  IconWallet,
  IconWashMachine,
  IconWifi,
  IconBike,
  IconPlane,
  type Icon,
} from '@tabler/icons-react'

import type { IconKey } from '@/lib/domain/look'

export const CATEGORY_ICONS: Record<IconKey, Icon> = {
  home: IconHome,
  tools: IconTools,
  bolt: IconBolt,
  flame: IconFlame,
  droplet: IconDroplet,
  wifi: IconWifi,
  phone: IconPhone,
  spray: IconSpray,
  laundry: IconWashMachine,

  basket: IconBasket,
  plant: IconPlant2,
  meat: IconMeat,
  kitchen: IconToolsKitchen2,
  coffee: IconCoffee,
  pizza: IconPizza,
  glass: IconGlassFull,
  cake: IconCake,

  bus: IconBus,
  car: IconCar,
  train: IconTrain,
  plane: IconPlane,
  bike: IconBike,
  fuel: IconGasStation,
  parking: IconParking,

  health: IconStethoscope,
  pill: IconPill,
  gym: IconBarbell,
  salon: IconScissors,

  movie: IconMovie,
  tv: IconDeviceTv,
  music: IconMusic,
  game: IconDeviceGamepad2,
  books: IconBook,
  ticket: IconTicket,

  card: IconCreditCard,
  cash: IconCash,
  bank: IconBuildingBank,
  shield: IconShieldCheck,
  chart: IconChartLine,
  piggy: IconPigMoney,
  wallet: IconWallet,
  briefcase: IconBriefcase,

  gift: IconGift,
  receipt: IconReceipt,
  school: IconSchool,
  family: IconUsers,
  pet: IconPaw,
  bag: IconShoppingBag,
  laptop: IconDeviceLaptop,
  heart: IconHeart,

  store: IconBuildingStore,
  coins: IconCoins,
  umbrella: IconUmbrella,
  certificate: IconCertificate,
  tag: IconTag,
}
